FROM ubuntu
RUN apt -y update
RUN apt -y upgrade
RUN apt -y install net-tools
RUN apt -y install openjdk-19-jre


#RUN mkdir /program
#WORKDIR /program
#COPY ./program/API-Rest.jar .
#COPY dockerIn/ .
#RUN chmod +x run.sh
#ENTRYPOINT ["/bin/bash", "-c", "./run.sh"]


 
